# Generated by Django 5.1.6 on 2025-02-28 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_expensecategory_monthlyexpense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ug', models.IntegerField()),
                ('nome_unidade', models.CharField(max_length=200)),
                ('ano', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('fonte_recurso', models.CharField(max_length=100)),
                ('valor_despesa', models.DecimalField(decimal_places=2, max_digits=15)),
                ('janeiro', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fevereiro', models.DecimalField(decimal_places=2, max_digits=15)),
                ('marco', models.DecimalField(decimal_places=2, max_digits=15)),
                ('abril', models.DecimalField(decimal_places=2, max_digits=15)),
                ('maio', models.DecimalField(decimal_places=2, max_digits=15)),
                ('junho', models.DecimalField(decimal_places=2, max_digits=15)),
                ('julho', models.DecimalField(decimal_places=2, max_digits=15)),
                ('agosto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('setembro', models.DecimalField(decimal_places=2, max_digits=15)),
                ('outubro', models.DecimalField(decimal_places=2, max_digits=15)),
                ('novembro', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dezembro', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'verbose_name': 'Cronograma de Desembolso',
                'verbose_name_plural': 'Cronogramas de Desembolso',
                'unique_together': {('ug', 'ano', 'fonte_recurso')},
            },
        ),
    ]
